version: '3'

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list

  compileAttributes:
    desc: Compile Rcpp attributes
    cmds:
      - R -e "Rcpp::compileAttributes()"

  manual:
    desc: Generate manual
    deps: [docs]
    cmds:
      - rm -f ../Manual.pdf
      - R CMD Rd2pdf . -o ../Manual.pdf

  docs:
    desc: Generate package documentation
    cmds:
      - R -e 'roxygen2::roxygenize(".", c("rd", "namespace"))'
      - sed -i '/RoxygenNote:.*/d' DESCRIPTION

  build:
    desc: Build the R package
    deps: [compileAttributes, docs]
    cmds:
      - R CMD build .

  build-fast:
    desc: Build the R package
    deps: [compileAttributes, docs]
    cmds:
      - R CMD build --no-build-vignettes .

  inst:
    desc: Install the R package
    deps: [build]
    cmds:
      - R CMD INSTALL infostop_*.tar.gz

  inst-fast:
    desc: Install the R package
    deps: [build-fast]
    cmds:
      - R CMD INSTALL infostop_*.tar.gz

  check:
    desc: Run R CMD check on the package
    deps: [build]
    cmds:
      - R CMD check infostop_*.tar.gz

  cran_check:
    desc: Run R CMD check on the package
    deps: [build]
    cmds:
      - R CMD check --as-cran infostop_*.tar.gz

  test:
    desc: Run tests with tinytest
    cmds:
      - R -e "tinytest::test_all()"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f infostop_*.tar.gz
      - rm -rf .Rhistory .RData infostop.Rcheck
      - rm -rf inst/doc
      - rm -rf Meta

  vignettes:
    desc: Build package vignettes
    cmds:
      - Rscript -e "devtools::build_vignettes()"

  tangle:
    desc: Run tangler to convert Rmd to R scripts
    cmds:
      - Rscript -e "setwd('vignettes'); knitr::knit('infostop.Rmd', tangle = TRUE)"

  tinytest-infostop:
    cmds:
      - R -e "tinytest::run_test_file('inst/tinytest/test_infostop.R')"

  test_infostop-py:
    cmds:
      - R -e "tinytest::run_test_file('inst/tinytest/test_infostop-py.R')"
