// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist_haversine_double
double dist_haversine_double(double lon1, double lat1, double lon2, double lat2, double radius);
RcppExport SEXP _infostopR_dist_haversine_double(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_haversine_double(lon1, lat1, lon2, lat2, radius));
    return rcpp_result_gen;
END_RCPP
}
// dist_haversine_cpp
NumericVector dist_haversine_cpp(NumericVector lon1, NumericVector lat1, NumericVector lon2, NumericVector lat2, double radius);
RcppExport SEXP _infostopR_dist_haversine_cpp(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_haversine_cpp(lon1, lat1, lon2, lat2, radius));
    return rcpp_result_gen;
END_RCPP
}
// get_stationary_events
Rcpp::List get_stationary_events(Rcpp::NumericVector lon, Rcpp::NumericVector lat, Rcpp::NumericVector time, double r_C, size_t min_size, double min_staying_time, double max_staying_time, std::string distance_metric);
RcppExport SEXP _infostopR_get_stationary_events(SEXP lonSEXP, SEXP latSEXP, SEXP timeSEXP, SEXP r_CSEXP, SEXP min_sizeSEXP, SEXP min_staying_timeSEXP, SEXP max_staying_timeSEXP, SEXP distance_metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type r_C(r_CSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type min_staying_time(min_staying_timeSEXP);
    Rcpp::traits::input_parameter< double >::type max_staying_time(max_staying_timeSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_metric(distance_metricSEXP);
    rcpp_result_gen = Rcpp::wrap(get_stationary_events(lon, lat, time, r_C, min_size, min_staying_time, max_staying_time, distance_metric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infostopR_dist_haversine_double", (DL_FUNC) &_infostopR_dist_haversine_double, 5},
    {"_infostopR_dist_haversine_cpp", (DL_FUNC) &_infostopR_dist_haversine_cpp, 5},
    {"_infostopR_get_stationary_events", (DL_FUNC) &_infostopR_get_stationary_events, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_infostopR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
