# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_haversine_double <- function(lon1, lat1, lon2, lat2, radius = 6378137.0) {
    .Call(`_infostop_dist_haversine_double`, lon1, lat1, lon2, lat2, radius)
}

dist_haversine_cpp <- function(lon1, lat1, lon2, lat2, radius = 6378137.0) {
    .Call(`_infostop_dist_haversine_cpp`, lon1, lat1, lon2, lat2, radius)
}

#' @noRd
.get_stationary_events_cpp <- function(lon, lat, time, r_C, min_size, min_staying_time, max_staying_time, distance_metric) {
    .Call(`_infostop_get_stationary_events`, lon, lat, time, r_C, min_size, min_staying_time, max_staying_time, distance_metric)
}

